// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_ventas.proto

package grpc;

public final class ControlVentas {
  private ControlVentas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VentaGRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VentaGRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idProducto = 1;</code>
     */
    java.lang.String getIdProducto();
    /**
     * <code>string idProducto = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdProductoBytes();

    /**
     * <code>double precio = 2;</code>
     */
    double getPrecio();

    /**
     * <code>int32 cantidad = 3;</code>
     */
    int getCantidad();
  }
  /**
   * Protobuf type {@code VentaGRPC}
   */
  public  static final class VentaGRPC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VentaGRPC)
      VentaGRPCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VentaGRPC.newBuilder() to construct.
    private VentaGRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VentaGRPC() {
      idProducto_ = "";
      precio_ = 0D;
      cantidad_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VentaGRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idProducto_ = s;
              break;
            }
            case 17: {

              precio_ = input.readDouble();
              break;
            }
            case 24: {

              cantidad_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ControlVentas.internal_static_VentaGRPC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ControlVentas.internal_static_VentaGRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ControlVentas.VentaGRPC.class, grpc.ControlVentas.VentaGRPC.Builder.class);
    }

    public static final int IDPRODUCTO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idProducto_;
    /**
     * <code>string idProducto = 1;</code>
     */
    public java.lang.String getIdProducto() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idProducto_ = s;
        return s;
      }
    }
    /**
     * <code>string idProducto = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdProductoBytes() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idProducto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRECIO_FIELD_NUMBER = 2;
    private double precio_;
    /**
     * <code>double precio = 2;</code>
     */
    public double getPrecio() {
      return precio_;
    }

    public static final int CANTIDAD_FIELD_NUMBER = 3;
    private int cantidad_;
    /**
     * <code>int32 cantidad = 3;</code>
     */
    public int getCantidad() {
      return cantidad_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdProductoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idProducto_);
      }
      if (precio_ != 0D) {
        output.writeDouble(2, precio_);
      }
      if (cantidad_ != 0) {
        output.writeInt32(3, cantidad_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdProductoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idProducto_);
      }
      if (precio_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, precio_);
      }
      if (cantidad_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cantidad_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.ControlVentas.VentaGRPC)) {
        return super.equals(obj);
      }
      grpc.ControlVentas.VentaGRPC other = (grpc.ControlVentas.VentaGRPC) obj;

      boolean result = true;
      result = result && getIdProducto()
          .equals(other.getIdProducto());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrecio())
          == java.lang.Double.doubleToLongBits(
              other.getPrecio()));
      result = result && (getCantidad()
          == other.getCantidad());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDPRODUCTO_FIELD_NUMBER;
      hash = (53 * hash) + getIdProducto().hashCode();
      hash = (37 * hash) + PRECIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrecio()));
      hash = (37 * hash) + CANTIDAD_FIELD_NUMBER;
      hash = (53 * hash) + getCantidad();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.ControlVentas.VentaGRPC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.VentaGRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.VentaGRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.VentaGRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.ControlVentas.VentaGRPC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VentaGRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VentaGRPC)
        grpc.ControlVentas.VentaGRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.ControlVentas.internal_static_VentaGRPC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.ControlVentas.internal_static_VentaGRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.ControlVentas.VentaGRPC.class, grpc.ControlVentas.VentaGRPC.Builder.class);
      }

      // Construct using grpc.ControlVentas.VentaGRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idProducto_ = "";

        precio_ = 0D;

        cantidad_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.ControlVentas.internal_static_VentaGRPC_descriptor;
      }

      @java.lang.Override
      public grpc.ControlVentas.VentaGRPC getDefaultInstanceForType() {
        return grpc.ControlVentas.VentaGRPC.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.ControlVentas.VentaGRPC build() {
        grpc.ControlVentas.VentaGRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.ControlVentas.VentaGRPC buildPartial() {
        grpc.ControlVentas.VentaGRPC result = new grpc.ControlVentas.VentaGRPC(this);
        result.idProducto_ = idProducto_;
        result.precio_ = precio_;
        result.cantidad_ = cantidad_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.ControlVentas.VentaGRPC) {
          return mergeFrom((grpc.ControlVentas.VentaGRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.ControlVentas.VentaGRPC other) {
        if (other == grpc.ControlVentas.VentaGRPC.getDefaultInstance()) return this;
        if (!other.getIdProducto().isEmpty()) {
          idProducto_ = other.idProducto_;
          onChanged();
        }
        if (other.getPrecio() != 0D) {
          setPrecio(other.getPrecio());
        }
        if (other.getCantidad() != 0) {
          setCantidad(other.getCantidad());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.ControlVentas.VentaGRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.ControlVentas.VentaGRPC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idProducto_ = "";
      /**
       * <code>string idProducto = 1;</code>
       */
      public java.lang.String getIdProducto() {
        java.lang.Object ref = idProducto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idProducto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdProductoBytes() {
        java.lang.Object ref = idProducto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idProducto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProducto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idProducto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder clearIdProducto() {
        
        idProducto_ = getDefaultInstance().getIdProducto();
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProductoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idProducto_ = value;
        onChanged();
        return this;
      }

      private double precio_ ;
      /**
       * <code>double precio = 2;</code>
       */
      public double getPrecio() {
        return precio_;
      }
      /**
       * <code>double precio = 2;</code>
       */
      public Builder setPrecio(double value) {
        
        precio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double precio = 2;</code>
       */
      public Builder clearPrecio() {
        
        precio_ = 0D;
        onChanged();
        return this;
      }

      private int cantidad_ ;
      /**
       * <code>int32 cantidad = 3;</code>
       */
      public int getCantidad() {
        return cantidad_;
      }
      /**
       * <code>int32 cantidad = 3;</code>
       */
      public Builder setCantidad(int value) {
        
        cantidad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cantidad = 3;</code>
       */
      public Builder clearCantidad() {
        
        cantidad_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VentaGRPC)
    }

    // @@protoc_insertion_point(class_scope:VentaGRPC)
    private static final grpc.ControlVentas.VentaGRPC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.ControlVentas.VentaGRPC();
    }

    public static grpc.ControlVentas.VentaGRPC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VentaGRPC>
        PARSER = new com.google.protobuf.AbstractParser<VentaGRPC>() {
      @java.lang.Override
      public VentaGRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VentaGRPC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VentaGRPC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VentaGRPC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.ControlVentas.VentaGRPC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BeneficioGRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BeneficioGRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double total = 1;</code>
     */
    double getTotal();
  }
  /**
   * Protobuf type {@code BeneficioGRPC}
   */
  public  static final class BeneficioGRPC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BeneficioGRPC)
      BeneficioGRPCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BeneficioGRPC.newBuilder() to construct.
    private BeneficioGRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BeneficioGRPC() {
      total_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BeneficioGRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              total_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ControlVentas.internal_static_BeneficioGRPC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ControlVentas.internal_static_BeneficioGRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ControlVentas.BeneficioGRPC.class, grpc.ControlVentas.BeneficioGRPC.Builder.class);
    }

    public static final int TOTAL_FIELD_NUMBER = 1;
    private double total_;
    /**
     * <code>double total = 1;</code>
     */
    public double getTotal() {
      return total_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (total_ != 0D) {
        output.writeDouble(1, total_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (total_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, total_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.ControlVentas.BeneficioGRPC)) {
        return super.equals(obj);
      }
      grpc.ControlVentas.BeneficioGRPC other = (grpc.ControlVentas.BeneficioGRPC) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getTotal())
          == java.lang.Double.doubleToLongBits(
              other.getTotal()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotal()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.BeneficioGRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.ControlVentas.BeneficioGRPC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BeneficioGRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BeneficioGRPC)
        grpc.ControlVentas.BeneficioGRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.ControlVentas.internal_static_BeneficioGRPC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.ControlVentas.internal_static_BeneficioGRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.ControlVentas.BeneficioGRPC.class, grpc.ControlVentas.BeneficioGRPC.Builder.class);
      }

      // Construct using grpc.ControlVentas.BeneficioGRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        total_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.ControlVentas.internal_static_BeneficioGRPC_descriptor;
      }

      @java.lang.Override
      public grpc.ControlVentas.BeneficioGRPC getDefaultInstanceForType() {
        return grpc.ControlVentas.BeneficioGRPC.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.ControlVentas.BeneficioGRPC build() {
        grpc.ControlVentas.BeneficioGRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.ControlVentas.BeneficioGRPC buildPartial() {
        grpc.ControlVentas.BeneficioGRPC result = new grpc.ControlVentas.BeneficioGRPC(this);
        result.total_ = total_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.ControlVentas.BeneficioGRPC) {
          return mergeFrom((grpc.ControlVentas.BeneficioGRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.ControlVentas.BeneficioGRPC other) {
        if (other == grpc.ControlVentas.BeneficioGRPC.getDefaultInstance()) return this;
        if (other.getTotal() != 0D) {
          setTotal(other.getTotal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.ControlVentas.BeneficioGRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.ControlVentas.BeneficioGRPC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double total_ ;
      /**
       * <code>double total = 1;</code>
       */
      public double getTotal() {
        return total_;
      }
      /**
       * <code>double total = 1;</code>
       */
      public Builder setTotal(double value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double total = 1;</code>
       */
      public Builder clearTotal() {
        
        total_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BeneficioGRPC)
    }

    // @@protoc_insertion_point(class_scope:BeneficioGRPC)
    private static final grpc.ControlVentas.BeneficioGRPC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.ControlVentas.BeneficioGRPC();
    }

    public static grpc.ControlVentas.BeneficioGRPC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BeneficioGRPC>
        PARSER = new com.google.protobuf.AbstractParser<BeneficioGRPC>() {
      @java.lang.Override
      public BeneficioGRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BeneficioGRPC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BeneficioGRPC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BeneficioGRPC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.ControlVentas.BeneficioGRPC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RestauranteGRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RestauranteGRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idRestaurante = 1;</code>
     */
    java.lang.String getIdRestaurante();
    /**
     * <code>string idRestaurante = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdRestauranteBytes();
  }
  /**
   * Protobuf type {@code RestauranteGRPC}
   */
  public  static final class RestauranteGRPC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RestauranteGRPC)
      RestauranteGRPCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RestauranteGRPC.newBuilder() to construct.
    private RestauranteGRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RestauranteGRPC() {
      idRestaurante_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RestauranteGRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idRestaurante_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ControlVentas.internal_static_RestauranteGRPC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ControlVentas.internal_static_RestauranteGRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ControlVentas.RestauranteGRPC.class, grpc.ControlVentas.RestauranteGRPC.Builder.class);
    }

    public static final int IDRESTAURANTE_FIELD_NUMBER = 1;
    private volatile java.lang.Object idRestaurante_;
    /**
     * <code>string idRestaurante = 1;</code>
     */
    public java.lang.String getIdRestaurante() {
      java.lang.Object ref = idRestaurante_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idRestaurante_ = s;
        return s;
      }
    }
    /**
     * <code>string idRestaurante = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdRestauranteBytes() {
      java.lang.Object ref = idRestaurante_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idRestaurante_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdRestauranteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idRestaurante_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdRestauranteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idRestaurante_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.ControlVentas.RestauranteGRPC)) {
        return super.equals(obj);
      }
      grpc.ControlVentas.RestauranteGRPC other = (grpc.ControlVentas.RestauranteGRPC) obj;

      boolean result = true;
      result = result && getIdRestaurante()
          .equals(other.getIdRestaurante());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDRESTAURANTE_FIELD_NUMBER;
      hash = (53 * hash) + getIdRestaurante().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.RestauranteGRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.ControlVentas.RestauranteGRPC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RestauranteGRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RestauranteGRPC)
        grpc.ControlVentas.RestauranteGRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.ControlVentas.internal_static_RestauranteGRPC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.ControlVentas.internal_static_RestauranteGRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.ControlVentas.RestauranteGRPC.class, grpc.ControlVentas.RestauranteGRPC.Builder.class);
      }

      // Construct using grpc.ControlVentas.RestauranteGRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idRestaurante_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.ControlVentas.internal_static_RestauranteGRPC_descriptor;
      }

      @java.lang.Override
      public grpc.ControlVentas.RestauranteGRPC getDefaultInstanceForType() {
        return grpc.ControlVentas.RestauranteGRPC.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.ControlVentas.RestauranteGRPC build() {
        grpc.ControlVentas.RestauranteGRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.ControlVentas.RestauranteGRPC buildPartial() {
        grpc.ControlVentas.RestauranteGRPC result = new grpc.ControlVentas.RestauranteGRPC(this);
        result.idRestaurante_ = idRestaurante_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.ControlVentas.RestauranteGRPC) {
          return mergeFrom((grpc.ControlVentas.RestauranteGRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.ControlVentas.RestauranteGRPC other) {
        if (other == grpc.ControlVentas.RestauranteGRPC.getDefaultInstance()) return this;
        if (!other.getIdRestaurante().isEmpty()) {
          idRestaurante_ = other.idRestaurante_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.ControlVentas.RestauranteGRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.ControlVentas.RestauranteGRPC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idRestaurante_ = "";
      /**
       * <code>string idRestaurante = 1;</code>
       */
      public java.lang.String getIdRestaurante() {
        java.lang.Object ref = idRestaurante_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idRestaurante_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idRestaurante = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdRestauranteBytes() {
        java.lang.Object ref = idRestaurante_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idRestaurante_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idRestaurante = 1;</code>
       */
      public Builder setIdRestaurante(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idRestaurante_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idRestaurante = 1;</code>
       */
      public Builder clearIdRestaurante() {
        
        idRestaurante_ = getDefaultInstance().getIdRestaurante();
        onChanged();
        return this;
      }
      /**
       * <code>string idRestaurante = 1;</code>
       */
      public Builder setIdRestauranteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idRestaurante_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RestauranteGRPC)
    }

    // @@protoc_insertion_point(class_scope:RestauranteGRPC)
    private static final grpc.ControlVentas.RestauranteGRPC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.ControlVentas.RestauranteGRPC();
    }

    public static grpc.ControlVentas.RestauranteGRPC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RestauranteGRPC>
        PARSER = new com.google.protobuf.AbstractParser<RestauranteGRPC>() {
      @java.lang.Override
      public RestauranteGRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RestauranteGRPC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RestauranteGRPC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RestauranteGRPC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.ControlVentas.RestauranteGRPC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductoGRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductoGRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idProducto = 1;</code>
     */
    java.lang.String getIdProducto();
    /**
     * <code>string idProducto = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdProductoBytes();

    /**
     * <code>int32 cantidad = 2;</code>
     */
    int getCantidad();
  }
  /**
   * Protobuf type {@code ProductoGRPC}
   */
  public  static final class ProductoGRPC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProductoGRPC)
      ProductoGRPCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductoGRPC.newBuilder() to construct.
    private ProductoGRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductoGRPC() {
      idProducto_ = "";
      cantidad_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductoGRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idProducto_ = s;
              break;
            }
            case 16: {

              cantidad_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ControlVentas.internal_static_ProductoGRPC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ControlVentas.internal_static_ProductoGRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ControlVentas.ProductoGRPC.class, grpc.ControlVentas.ProductoGRPC.Builder.class);
    }

    public static final int IDPRODUCTO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idProducto_;
    /**
     * <code>string idProducto = 1;</code>
     */
    public java.lang.String getIdProducto() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idProducto_ = s;
        return s;
      }
    }
    /**
     * <code>string idProducto = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdProductoBytes() {
      java.lang.Object ref = idProducto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idProducto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANTIDAD_FIELD_NUMBER = 2;
    private int cantidad_;
    /**
     * <code>int32 cantidad = 2;</code>
     */
    public int getCantidad() {
      return cantidad_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdProductoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idProducto_);
      }
      if (cantidad_ != 0) {
        output.writeInt32(2, cantidad_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdProductoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idProducto_);
      }
      if (cantidad_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cantidad_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.ControlVentas.ProductoGRPC)) {
        return super.equals(obj);
      }
      grpc.ControlVentas.ProductoGRPC other = (grpc.ControlVentas.ProductoGRPC) obj;

      boolean result = true;
      result = result && getIdProducto()
          .equals(other.getIdProducto());
      result = result && (getCantidad()
          == other.getCantidad());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDPRODUCTO_FIELD_NUMBER;
      hash = (53 * hash) + getIdProducto().hashCode();
      hash = (37 * hash) + CANTIDAD_FIELD_NUMBER;
      hash = (53 * hash) + getCantidad();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.ProductoGRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.ProductoGRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ControlVentas.ProductoGRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.ControlVentas.ProductoGRPC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductoGRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductoGRPC)
        grpc.ControlVentas.ProductoGRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.ControlVentas.internal_static_ProductoGRPC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.ControlVentas.internal_static_ProductoGRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.ControlVentas.ProductoGRPC.class, grpc.ControlVentas.ProductoGRPC.Builder.class);
      }

      // Construct using grpc.ControlVentas.ProductoGRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idProducto_ = "";

        cantidad_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.ControlVentas.internal_static_ProductoGRPC_descriptor;
      }

      @java.lang.Override
      public grpc.ControlVentas.ProductoGRPC getDefaultInstanceForType() {
        return grpc.ControlVentas.ProductoGRPC.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.ControlVentas.ProductoGRPC build() {
        grpc.ControlVentas.ProductoGRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.ControlVentas.ProductoGRPC buildPartial() {
        grpc.ControlVentas.ProductoGRPC result = new grpc.ControlVentas.ProductoGRPC(this);
        result.idProducto_ = idProducto_;
        result.cantidad_ = cantidad_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.ControlVentas.ProductoGRPC) {
          return mergeFrom((grpc.ControlVentas.ProductoGRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.ControlVentas.ProductoGRPC other) {
        if (other == grpc.ControlVentas.ProductoGRPC.getDefaultInstance()) return this;
        if (!other.getIdProducto().isEmpty()) {
          idProducto_ = other.idProducto_;
          onChanged();
        }
        if (other.getCantidad() != 0) {
          setCantidad(other.getCantidad());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.ControlVentas.ProductoGRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.ControlVentas.ProductoGRPC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idProducto_ = "";
      /**
       * <code>string idProducto = 1;</code>
       */
      public java.lang.String getIdProducto() {
        java.lang.Object ref = idProducto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idProducto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdProductoBytes() {
        java.lang.Object ref = idProducto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idProducto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProducto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idProducto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder clearIdProducto() {
        
        idProducto_ = getDefaultInstance().getIdProducto();
        onChanged();
        return this;
      }
      /**
       * <code>string idProducto = 1;</code>
       */
      public Builder setIdProductoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idProducto_ = value;
        onChanged();
        return this;
      }

      private int cantidad_ ;
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public int getCantidad() {
        return cantidad_;
      }
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public Builder setCantidad(int value) {
        
        cantidad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cantidad = 2;</code>
       */
      public Builder clearCantidad() {
        
        cantidad_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProductoGRPC)
    }

    // @@protoc_insertion_point(class_scope:ProductoGRPC)
    private static final grpc.ControlVentas.ProductoGRPC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.ControlVentas.ProductoGRPC();
    }

    public static grpc.ControlVentas.ProductoGRPC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductoGRPC>
        PARSER = new com.google.protobuf.AbstractParser<ProductoGRPC>() {
      @java.lang.Override
      public ProductoGRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductoGRPC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductoGRPC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductoGRPC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.ControlVentas.ProductoGRPC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VentaGRPC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VentaGRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BeneficioGRPC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BeneficioGRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RestauranteGRPC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RestauranteGRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductoGRPC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductoGRPC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024control_ventas.proto\"A\n\tVentaGRPC\022\022\n\ni" +
      "dProducto\030\001 \001(\t\022\016\n\006precio\030\002 \001(\001\022\020\n\010canti" +
      "dad\030\003 \001(\005\"\036\n\rBeneficioGRPC\022\r\n\005total\030\001 \001(" +
      "\001\"(\n\017RestauranteGRPC\022\025\n\ridRestaurante\030\001 " +
      "\001(\t\"4\n\014ProductoGRPC\022\022\n\nidProducto\030\001 \001(\t\022" +
      "\020\n\010cantidad\030\002 \001(\0052t\n\017ControlDeVentas\0220\n\016" +
      "registrarVenta\022\n.VentaGRPC\032\016.BeneficioGR" +
      "PC\"\000(\001\022/\n\006ventas\022\020.RestauranteGRPC\032\r.Pro" +
      "ductoGRPC\"\000(\0010\001B\006\n\004grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VentaGRPC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VentaGRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VentaGRPC_descriptor,
        new java.lang.String[] { "IdProducto", "Precio", "Cantidad", });
    internal_static_BeneficioGRPC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BeneficioGRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BeneficioGRPC_descriptor,
        new java.lang.String[] { "Total", });
    internal_static_RestauranteGRPC_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RestauranteGRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RestauranteGRPC_descriptor,
        new java.lang.String[] { "IdRestaurante", });
    internal_static_ProductoGRPC_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ProductoGRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductoGRPC_descriptor,
        new java.lang.String[] { "IdProducto", "Cantidad", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
